apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sso-integration
  namespace: ansible-automation-platform
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - patch 
      - create
  - apiGroups:
      - "route.openshift.io"
    resources:
      - routes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sso-integration
  namespace: ansible-automation-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sso-integration
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sso-integration