apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sso-integration
  namespace: openshift-authentication
rules:
  - apiGroups:
      - "route.openshift.io"
    resources:
      - routes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sso-integration
  namespace: openshift-authentication
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sso-integration
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sso-integration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sso-integration
  namespace: openshift-config
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - delete
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sso-integration
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sso-integration
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sso-integration