apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - secretstore.yaml
  - sso-configs-es.yaml
  - keycloak-pre-processing-job.yaml

patches:
- target:
    group: external-secrets.io
    kind: SecretStore
    labelSelector: "sso-integration-component=preprocessing-secretstore"
  patch: |-
    - op: replace
      path: /spec/provider/vault/caBundle
      value: TUlJREdEQ0NBZ0NnQXdJQkFnSVFlMGlkVE5TSTJqcDVzcmUraU45WUhqQU5CZ2txaGtpRzl3MEJBUXNGQURBbQpNU1F3SWdZRFZRUURFeHRqWVM1elpXeG1MWE5wWjI1bGNpNWpaWEowTFcxaGJtRm5aWEl3SGhjTk1qSXdNakF5Ck1qRXpNVEkwV2hjTk1qSXdOVEF6TWpFek1USTBXakFtTVNRd0lnWURWUVFERXh0allTNXpaV3htTFhOcFoyNWwKY2k1alpYSjBMVzFoYm1GblpYSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEYQpuSFZoZUZLTEwvcE8xUkJrMkRPbUFFTjRCSHZaY0VSMlFhbWZRUURsbnVCRDYyTWR2U0xrNU9BcUtnWS9SMWtqCi9mZGhvaVdFQ2wyRGh6YWluY0QwWGpHbHd3SkUyTEpyUWx2MHhOOG9yd2ozSFhLcUIyK0xVS1J4QlJraWU1TTgKUXR1b21VVWxialhoQTVSVHIxcXJJeE0ySTNKQ3U2S1BPTS9rU1RBdlZEcXFwWlI4ME5LamkyNXptaGJXSTBOOQp3KzRLdk9pME5MRUdVOUg0dW81NENGMzZjTEdmcE8yV0RxSi9yYWpaeUFDMi91U1k4RjBHWURmVW14MDFOQ3lMCjFTK3lGMVhIM3JsZjltcFhORHlCWTNmaW1TTTJmWjk4eDlPRjZheXF3K0NPVjA3bDh3OFJqLzlDMXVnVUw5RnYKNHliS0U2MGp4NHY2YklOMnk4WHBBZ01CQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQgpBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNoV29GRzd0elp2Y0lxeUk5bnBnYUQxcnRGU2pBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFLZVc4Q2QvRSthWmF6R1NXNFN5QzI1Q2RaamphVGtSNFU1djM2dEVzZ0ltMzJyT0kKNnc0azhxNDQ3RUlhVGp0RkNqNERRYVlNNFpqOUdUWnVYMlpVR3FGb1l3TWhBZURhWmhJWG9neDRCNDk4NlNJdQorcHUyZ3Roc294N3FHazhyakd6L2ZpaG9XR3BaTTRJY3Z5RTFjRFdHeVpNeUtkbEpXQ1VUMmxjOUVaYzRzOEIzCm1Nc3dXdEgyUHR4V2VoMU5tdkpINHVuRnVzYTZPZTZpVlphbG55RlMxUlVKeVNLTXdzZ0tKS0dtZTBVdHhpTUMKNXdJLzlad25WdjZRc2xzL0FVeHlGSnZGU3preXlwM1lWRllVMEl4cjFpYktnOGZJa2NVc2ZBZVd3d0VqRTBiYgpKMTk1dko1NWw4ZXlyN2g5Sk5OM1pNRXY4TmRQVktmV2NDNEthQT09
    - op: replace
      path: /spec/provider/vault/server
      value: https://vault.apps.aws0.mutihybridcloudkitchen.com:443
