apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - secretstore.yaml
  - sso-configs-es.yaml
  - keycloak-pre-processing-job.yaml

patches:
- target:
    group: external-secrets.io
    kind: SecretStore
    labelSelector: "sso-integration-component=preprocessing-secretstore"
  patch: |-
    - op: replace
      path: /spec/provider/vault/caBundle
      value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2ekNDQWt5Z0F3SUJBZ0lVSTdiNjhwMHBQckNCb1c0cHRseXZWY1BJdHNjd0NnWUlLb1pJemowRUF3UXcKZ1kweEN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUlFd3BEWVd4cFptOXlibWxoTVJZd0ZBWURWUVFIRXcxVApZVzRnUm5KaGJtTnBjMk52TVJnd0ZnWURWUVFLRXc5RGJHOTFaR1pzWVhKbExDQkpibU14TnpBMUJnTlZCQU1UCkxrTnNiM1ZrWm14aGNtVWdabTl5SUZSbFlXMXpJRVZEUXlCRFpYSjBhV1pwWTJGMFpTQkJkWFJvYjNKcGRIa3cKSGhjTk1qQXdNakEwTVRZd05UQXdXaGNOTWpVd01qQXlNVFl3TlRBd1dqQ0JqVEVMTUFrR0ExVUVCaE1DVlZNeApFekFSQmdOVkJBZ1RDa05oYkdsbWIzSnVhV0V4RmpBVUJnTlZCQWNURFZOaGJpQkdjbUZ1WTJselkyOHhHREFXCkJnTlZCQW9URDBOc2IzVmtabXhoY21Vc0lFbHVZekUzTURVR0ExVUVBeE11UTJ4dmRXUm1iR0Z5WlNCbWIzSWcKVkdWaGJYTWdSVU5ESUVObGNuUnBabWxqWVhSbElFRjFkR2h2Y21sMGVUQ0JtekFRQmdjcWhrak9QUUlCQmdVcgpnUVFBSXdPQmhnQUVBVmRYc1g4dHBBOU5BUWVFUWFsdlVJY1ZhRk5EdkdzUjY5eXNaeE9yYVJXTkdITGZxMW1pClA2bzN3dG10eC9DMk9YRzAxQ3c3VUZKYktsNU1FRHhuVDJLb0FkRlN5blNKT0YyTkRvZTVMb1pIYlVXK3lSM1gKRkRsK01GNkp6WjU5MFZMR282ZFBCZjA2VXNYYkg3UHZISDJYS3RGdDhiQlhWTk1hNWEyMVJkbXBEMFBobzBVdwpRekFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBakFkQmdOVkhRNEVGZ1FVCllCY1FuZzFBRU1NTnRldVJEQU1HMC92Z0ZlMHdDZ1lJS29aSXpqMEVBd1FEZ1l3QU1JR0lBa0lCUVU1T1RBMmgKWXFtRms4cGFhbjVlekhWTGNtY3Vjc2ZZdzRML3dtZUVqQ2tjelJtQ1ZObTZMODZMamhXVTB2MHdFUjBlK2xITwozZWZ2amJzdThnSUdTYWdDUWdFQm55WU1QOWd3ZzhsOTZRblExa2hGQTFsakZsbnFjMlhnSkhEU2FBSkMwZ2R6CitOVjNKTWVXYUQyUmIzMmpjOXI2L2E3eFkwdTBCeXF4QlExT1EwZHQ3QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    - op: replace
      path: /spec/provider/vault/server
      value: https://vault.swinney.io:443
