apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - secretstore.yaml
  - sso-configs-es.yaml
  - keycloak-pre-processing-job.yaml

patches:
- target:
    group: external-secrets.io
    kind: SecretStore
    labelSelector: "sso-integration-component=preprocessing-secretstore"
  patch: |-
    - op: replace
      path: /spec/provider/vault/caBundle
      value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ3VENDQVVpZ0F3SUJBZ0lSQU5ZbFRjRnQ5bk5Oa05hemFQZnVycnN3Q2dZSUtvWkl6ajBFQXdNd0lqRWcKTUI0R0ExVUVBeE1YWTJWeWRDMXRZVzVoWjJWeUxYZGxZbWh2YjJzdFkyRXdIaGNOTWpJd01qQXlNakV6TURVegpXaGNOTWpNd01qQXlNakV6TURVeldqQWlNU0F3SGdZRFZRUURFeGRqWlhKMExXMWhibUZuWlhJdGQyVmlhRzl2CmF5MWpZVEIyTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQTJJQUJGN090SUd3bloybzEvNWFEQVFQVDloWjltbmEKcUxjS2ZTSTFGK2I1NlloaVNudnR0bTlNcTJPbloreE9JSTJBVXpscUVLUjdVY2pEMElYWlM5R2svZHBnQ21qaQpHZktOc3NPY2VZQzdWMU84NjdLV3Z4d1lENEs5RkJZVFpBdHBWcU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trCk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNMVhlL2IwbGlXUm9GcEt3bzVYR3hjZzh0ZzcKTUFvR0NDcUdTTTQ5QkFNREEyY0FNR1FDTUI0Sms0TXdXUUkxL2ZJdGtRQVVRc2h1VlE1Y2NRQzNtd0ZCbE9odApLMUVIanMxS2ZKWHl6ZjRDM0JqcVgwVlFIQUl3YjRka1VTNFNiaXpaTDVURThsNWVZdDg3TVcrYTFUb1JiOTJ0CmlHOVhSdWFieUtOSWJ1WEs0VUxlUHhOcXphOXoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    - op: replace
      path: /spec/provider/vault/server
      value: https://vault.swinney.io:443
