apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sso-integration
  namespace: sso
rules:
  - apiGroups:
      - "route.openshift.io"
    resources:
      - routes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sso-integration
  namespace: sso
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sso-integration
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sso-integration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sso-integration
  namespace: sso-integration
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - patch
      - list
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - patch
      - list
      - create
  - apiGroups:
      - "external-secrets.io"
    resources:
      - secretstores
    verbs:
      - get
      - patch
      - list
      - create
      - delete
  - apiGroups:
      - "external-secrets.io"
    resources:
      - externalsecrets
    verbs:
      - get
      - patch
      - list
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sso-integration
  namespace: sso-integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sso-integration
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-cntk-argocd-application-controller
    namespace: openshift-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sso-integration-default
  namespace: sso-integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sso-integration
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sso-integration