apiVersion: batch/v1
kind: Job
metadata:
  name: azure-keycloak-integration
  namespace: sso-integration
spec:
  template:
    spec:
      containers:
      - name: azure-keycloak-integration
        image: quay.io/mahesh_v/azure-keycloak-integration:v1
        envFrom:
        - configMapRef:
            name: argocd-configs
        - secretRef:
            name: sso-configs
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 5
